name: Require Labels
description: Require labels to be added to a pull request before merging
runs:
  using: docker
  image: Dockerfile
branding:
  icon: check-square
  color: blue
inputs:
  token:
    description: The GitHub token to use when calling the API
    default: ${{ github.token }}
    required: false
  labels:
    description: "Comma separated list of labels to match"
    required: true
  mode:
    description: "The mode of comparison to use. One of: exactly, minimum, maximum"
    required: true
  count:
    description: "The required number of labels to match"
    required: true
  add_comment:
    description: "Add a comment to the PR if required labels are missing"
    default: "false"
    required: false
  exit_type:
    description: "The exit type of the action. One of: failure, success, neutral"
    required: false
